In [15]:
import cv2
import numpy as np

In [10]:
city_label_path = r'/root/tqdm/datasets/cityscapes/gtFine/test/berlin/berlin_000527_000019_gtFine_labelTrainIds.png'
city_label_path = r'/root/tqdm/datasets/gta/data/labels/train/23003_labelTrainIds.png'

In [3]:
orfd_label_path = r'/root/tqdm/datasets/ORFD/training/c2021_0228_1819/gt_image/1620331020738_fillcolor.png'

In [11]:
city_label = cv2.imread(city_label_path)

In [5]:
orfd_label = cv2.imread(orfd_label_path)

In [6]:
city_label.shape

(1024, 2048, 3)

In [7]:
orfd_label.shape

(720, 1280, 3)

In [12]:
city_label

array([[[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10],
        ...,
        [ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [9]:
orfd_label

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [16]:
np.unique(city_label)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,
        14,  16, 255], dtype=uint8)

In [17]:
np.unique(orfd_label)

array([  0, 128, 255], dtype=uint8)